apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: models
  namespace: hanzo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - models.hanzo.ai
      secretName: models-tls
  rules:
    - host: models.hanzo.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: models
                port:
                  number: 8080
