apiVersion: secrets.lux.network/v1alpha1
kind: KMSSecret
metadata:
  name: models-kms-sync
  namespace: hanzo
spec:
  hostAPI: https://kms.hanzo.ai
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: models-kms-auth
        secretNamespace: hanzo
      secretsScope:
        projectSlug: models
        envSlug: production
        secretsPath: /
  managedSecretReference:
    secretName: models-secrets
    secretNamespace: hanzo
    secretType: Opaque
